<?php
declare(strict_types=1);
class IrrigationArea extends IPSModule
{
 private const MODE_MANUAL=1,MODE_TIME=2,MODE_AUTO=3; private const MODULE_ID_ZONE='{B69A3F87-2E64-4AA0-B67E-7D84587B8A11}';
 public function Create(){parent::Create();$this->RegisterPropertyBoolean('Enabled',true);$this->RegisterPropertyInteger('AreaNumber',1);$this->RegisterPropertyInteger('Mode',self::MODE_MANUAL);$this->RegisterPropertyInteger('PauseBetweenZonesSeconds',5);$this->RegisterPropertyInteger('MaxZones',10);$this->RegisterVariableBoolean('Enabled','Zone aktiv','~Switch',10);$this->EnableAction('Enabled');$this->RegisterVariableInteger('AreaNumber','Zonennummer','',20);$this->RegisterVariableInteger('Mode','Betriebsmodus','IRR.Mode',30);$this->EnableAction('Mode');$this->RegisterVariableBoolean('AreaActive','Zone läuft','~Switch',40);$this->EnableAction('AreaActive');$this->RegisterVariableInteger('CurrentZone','Aktueller Kreis','',50);$this->RegisterVariableInteger('QueueCount','Wartende Kreise','',60);$this->RegisterVariableString('LastAction','Letzte 10 Aktionen','~HTMLBox',80);$this->RegisterVariableString('ZoneOverview','Kreisübersicht','~HTMLBox',90);$this->RegisterTimer('StartNextZoneTimer',0,'IRRA_StartNextZone($_IPS[\'TARGET\']);');$this->RegisterTimer('StopCurrentZoneTimer',0,'IRRA_FinishCurrentZone($_IPS[\'TARGET\']);');$this->SetBuffer('Queue',json_encode([]));$this->SetBuffer('CurrentZoneID','0');}
 public function ApplyChanges(){parent::ApplyChanges();$this->SetValue('Enabled',$this->ReadPropertyBoolean('Enabled'));$this->SetValue('AreaNumber',$this->ReadPropertyInteger('AreaNumber'));$this->SetValue('Mode',$this->ReadPropertyInteger('Mode'));$this->RefreshZones();}
 public function GetConfigurationForm(){return file_get_contents(__DIR__.'/form.json');}
 public function RequestAction($Ident,$Value){switch($Ident){case'Enabled':IPS_SetProperty($this->InstanceID,'Enabled',(bool)$Value);IPS_ApplyChanges($this->InstanceID);break;case'Mode':IPS_SetProperty($this->InstanceID,'Mode',(int)$Value);IPS_ApplyChanges($this->InstanceID);break;case'AreaActive':(bool)$Value?$this->StartArea(false):$this->StopArea(false);break;default:throw new Exception('Unbekannte Aktion: '.$Ident);}}
 public function IsEnabled():bool{return $this->ReadPropertyBoolean('Enabled');} public function GetAreaNumber():int{return $this->ReadPropertyInteger('AreaNumber');}
 public function CreateZone():void{$zones=$this->GetZones();$n=1;$used=[];foreach($zones as $id){$used[]=@IRRZ_GetZoneNumber($id);}while(in_array($n,$used,true))$n++;$id=IPS_CreateInstance(self::MODULE_ID_ZONE);IPS_SetParent($id,$this->InstanceID);IPS_SetName($id,'Kreis '.$n);IPS_SetPosition($id,1000+$n);IPS_SetProperty($id,'ZoneNumber',$n);IPS_ApplyChanges($id);$this->RefreshZones();$this->WriteLog('Kreis '.$n.' angelegt');}
 public function RefreshZones():void{$p=[];foreach($this->GetZones() as $id){$p[]='Kreis '.@IRRZ_GetZoneNumber($id).' (#'.$id.')';}$this->SetValue('ZoneOverview',implode('<br>',$p));}
 public function StartArea(bool $FromMaster=false):void{$zones=$this->GetRunnableZones();if(!$zones){$this->WriteLog('Keine Kreise zu bewässern');return;}$this->SetBuffer('Queue',json_encode($zones));$this->SetValue('AreaActive',true);$this->SetValue('QueueCount',count($zones));$this->WriteLog('Zone gestartet');$this->SetTimerInterval('StartNextZoneTimer',100);}
 public function StopArea(bool $FromMaster=false):void{$this->SetTimerInterval('StartNextZoneTimer',0);$this->SetTimerInterval('StopCurrentZoneTimer',0);$id=(int)$this->GetBuffer('CurrentZoneID');if($id>0)@IRRZ_StopZone($id,true);$this->SetValue('AreaActive',false);$this->SetValue('CurrentZone',0);$this->SetValue('QueueCount',0);$this->SetBuffer('Queue',json_encode([]));$this->WriteLog('Zone gestoppt');}
 public function StartNextZone():void{$this->SetTimerInterval('StartNextZoneTimer',0);$q=json_decode($this->GetBuffer('Queue'),true)?:[];if(!$q){$this->SetValue('AreaActive',false);$this->WriteLog('Zone abgeschlossen');return;}$id=array_shift($q);$this->SetBuffer('Queue',json_encode($q));$this->SetBuffer('CurrentZoneID',(string)$id);$this->SetValue('CurrentZone',@IRRZ_GetZoneNumber($id));$this->SetValue('QueueCount',count($q));$this->WriteLog('Starte Kreis '.@IRRZ_GetZoneNumber($id));@IRRZ_StartZone($id,true);$dur=max(1,(int)@IRRZ_GetDurationMinutes($id));$this->SetTimerInterval('StopCurrentZoneTimer',$dur*60*1000);}
 public function FinishCurrentZone():void{$this->SetTimerInterval('StopCurrentZoneTimer',0);$id=(int)$this->GetBuffer('CurrentZoneID');if($id>0)@IRRZ_StopZone($id,true);$q=json_decode($this->GetBuffer('Queue'),true)?:[];if(!$q){$this->SetValue('AreaActive',false);$this->WriteLog('Zone abgeschlossen');return;}$pause=max(0,$this->ReadPropertyInteger('PauseBetweenZonesSeconds'))*1000;$this->SetTimerInterval('StartNextZoneTimer',max(100,$pause));}
 private function GetRunnableZones():array{$r=[];$auto=$this->ReadPropertyInteger('Mode')===self::MODE_AUTO;foreach($this->GetZones() as $id){if(!@IRRZ_IsEnabled($id))continue;if($auto&&!@IRRZ_ShouldWater($id))continue;$r[]=$id;}return $r;}
 private function GetZones():array{$r=[];foreach(IPS_GetChildrenIDs($this->InstanceID) as $id){if(@IPS_InstanceExists($id)&&strtoupper(IPS_GetInstance($id)['ModuleInfo']['ModuleID']??'')===strtoupper(self::MODULE_ID_ZONE))$r[]=$id;}usort($r,fn($a,$b)=>@IRRZ_GetZoneNumber($a)<=>@IRRZ_GetZoneNumber($b));return $r;}
 private function WriteLog(string $m):void{$a=[];$raw=strip_tags($this->GetValue('LastAction'));if($raw)$a=explode("\n",str_replace('<br>',"\n",$raw));$a[]='['.date('H:i:s').'] '.$m;$a=array_slice($a,-10);$this->SetValue('LastAction','<div style="font-family:Tahoma;font-size:12px;color:white;text-align:right;">'.implode('<br>',array_map('htmlspecialchars',$a)).'</div>');}
}
function IRRA_CreateZone($id){return (new IrrigationArea($id))->CreateZone();} function IRRA_RefreshZones($id){return (new IrrigationArea($id))->RefreshZones();} function IRRA_StartArea($id,$m=false){return (new IrrigationArea($id))->StartArea($m);} function IRRA_StopArea($id,$m=false){return (new IrrigationArea($id))->StopArea($m);} function IRRA_StartNextZone($id){return (new IrrigationArea($id))->StartNextZone();} function IRRA_FinishCurrentZone($id){return (new IrrigationArea($id))->FinishCurrentZone();} function IRRA_IsEnabled($id){return (new IrrigationArea($id))->IsEnabled();} function IRRA_GetAreaNumber($id){return (new IrrigationArea($id))->GetAreaNumber();}
