<?php
declare(strict_types=1);
class IrrigationZone extends IPSModule
{
 private const MOISTURE_LOWEST=0,MOISTURE_AVERAGE=1;
 public function Create(){parent::Create();$this->RegisterPropertyBoolean('Enabled',true);$this->RegisterPropertyInteger('ZoneNumber',1);$this->RegisterPropertyInteger('Duration',10);$this->RegisterPropertyInteger('MoistureThreshold',35);$this->RegisterPropertyInteger('MoistureMode',self::MOISTURE_LOWEST);$this->RegisterPropertyInteger('MoistureSensor1',0);$this->RegisterPropertyInteger('MoistureSensor2',0);$this->RegisterPropertyInteger('RainLast24h',0);$this->RegisterPropertyInteger('RainThreshold24h',0);$this->RegisterPropertyInteger('Actuator1Instance',0);$this->RegisterPropertyInteger('Actuator2Instance',0);$this->RegisterPropertyInteger('DelayBetweenActuatorsMs',500);$this->RegisterVariableBoolean('Enabled','Kreis aktiv','~Switch',10);$this->EnableAction('Enabled');$this->RegisterVariableInteger('ZoneNumber','Kreisnummer','',20);$this->RegisterVariableInteger('DurationMinutes','Beregnungsdauer','IRR.Minutes',30);$this->EnableAction('DurationMinutes');$this->RegisterVariableBoolean('ZoneActive','Kreis aktiv bewässert','~Switch',70);$this->EnableAction('ZoneActive');$this->RegisterVariableBoolean('ShouldWater','Automatik: Bewässern','~Switch',140);$this->RegisterVariableString('LastAction','Letzte 4 Aktionen','~HTMLBox',160);}
 public function ApplyChanges(){parent::ApplyChanges();$this->SetValue('Enabled',$this->ReadPropertyBoolean('Enabled'));$this->SetValue('ZoneNumber',$this->ReadPropertyInteger('ZoneNumber'));$this->SetValue('DurationMinutes',$this->ReadPropertyInteger('Duration'));$this->SetValue('ShouldWater',$this->ShouldWater());}
 public function GetConfigurationForm(){return file_get_contents(__DIR__.'/form.json');}
 public function RequestAction($Ident,$Value){switch($Ident){case'Enabled':IPS_SetProperty($this->InstanceID,'Enabled',(bool)$Value);IPS_ApplyChanges($this->InstanceID);break;case'DurationMinutes':IPS_SetProperty($this->InstanceID,'Duration',max(1,(int)$Value));IPS_ApplyChanges($this->InstanceID);break;case'ZoneActive':(bool)$Value?$this->StartZone(false):$this->StopZone(false);break;}}
 public function IsEnabled():bool{return $this->ReadPropertyBoolean('Enabled');} public function GetZoneNumber():int{return $this->ReadPropertyInteger('ZoneNumber');} public function GetDurationMinutes():int{return $this->ReadPropertyInteger('Duration');}
 public function ShouldWater():bool{if(!$this->ReadPropertyBoolean('Enabled'))return false;$v=$this->ReadNumericPropertyVariable('MoistureSensor1');$t=$this->ReadPropertyInteger('MoistureThreshold');return $v===null?true:$v<$t;}
 public function StartZone(bool $FromMaster=false):void{$this->SetActuator(2,true);if($this->ReadPropertyInteger('DelayBetweenActuatorsMs')>0)IPS_Sleep($this->ReadPropertyInteger('DelayBetweenActuatorsMs'));$this->SetActuator(1,true);$this->SetValue('ZoneActive',true);$this->WriteLog('Kreis gestartet');}
 public function StopZone(bool $FromMaster=false):void{$this->SetActuator(2,false);if($this->ReadPropertyInteger('DelayBetweenActuatorsMs')>0)IPS_Sleep($this->ReadPropertyInteger('DelayBetweenActuatorsMs'));$this->SetActuator(1,false);$this->SetValue('ZoneActive',false);$this->WriteLog('Kreis gestoppt');}
 private function SetActuator(int $n,bool $s):void{$id=$this->ReadPropertyInteger($n===1?'Actuator1Instance':'Actuator2Instance');if($id<=0)return;if(@IPS_VariableExists($id)){@RequestAction($id,$s);return;}if(@IPS_InstanceExists($id)){foreach(IPS_GetChildrenIDs($id) as $c){if(@IPS_VariableExists($c)&&IPS_GetVariable($c)['VariableType']===VARIABLETYPE_BOOLEAN&&IPS_GetVariable($c)['VariableAction']>0){@RequestAction($c,$s);return;}}}}
 private function ReadNumericPropertyVariable(string $p):?float{$id=$this->ReadPropertyInteger($p);if($id<=0||!@IPS_VariableExists($id))return null;$v=@GetValue($id);return is_numeric($v)?(float)$v:null;}
 private function WriteLog(string $m):void{$a=[];$raw=strip_tags($this->GetValue('LastAction'));if($raw)$a=explode("\n",str_replace('<br>',"\n",$raw));$a[]='['.date('H:i:s').'] '.$m;$a=array_slice($a,-4);$this->SetValue('LastAction','<div style="font-family:Tahoma;font-size:12px;color:white;text-align:right;">'.implode('<br>',array_map('htmlspecialchars',$a)).'</div>');}
}
function IRRZ_StartZone($id,$m=false){return (new IrrigationZone($id))->StartZone($m);} function IRRZ_StopZone($id,$m=false){return (new IrrigationZone($id))->StopZone($m);} function IRRZ_IsEnabled($id){return (new IrrigationZone($id))->IsEnabled();} function IRRZ_GetZoneNumber($id){return (new IrrigationZone($id))->GetZoneNumber();} function IRRZ_GetDurationMinutes($id){return (new IrrigationZone($id))->GetDurationMinutes();} function IRRZ_ShouldWater($id){return (new IrrigationZone($id))->ShouldWater();}
