<?php
declare(strict_types=1);
class IrrigationController extends IPSModule
{
    private const MODULE_ID_AREA = '{C6A0D3B7-3E8B-4B74-9F1D-7E5F1D5A9A21}';
    public function Create(){parent::Create();$this->RegisterPropertyInteger('PumpLeadTimeSeconds',5);$this->RegisterPropertyInteger('PumpEarlyOffSeconds',0);$this->RegisterPropertyInteger('PauseBetweenAreasSeconds',5);$this->RegisterPropertyInteger('MaxAreas',10);$this->RegisterPropertyInteger('PumpInstance',0);$this->RegisterPropertyInteger('PumpVariable',0);$this->RegisterVariableBoolean('SequenceActive','Sequenz aktiv','~Switch',50);$this->EnableAction('SequenceActive');$this->RegisterVariableBoolean('PumpActive','Pumpe aktiv','~Switch',60);$this->RegisterVariableInteger('CurrentArea','Aktuelle Zone','',70);$this->RegisterVariableInteger('QueueCount','Wartende Zonen','',80);$this->RegisterVariableString('LastAction','Letzte 10 Aktionen','~HTMLBox',100);$this->RegisterVariableString('AreaOverview','Zonenübersicht','~HTMLBox',110);$this->RegisterTimer('StartNextAreaTimer',0,'IRR_StartNextArea($_IPS[\'TARGET\']);');$this->SetBuffer('AreaQueue',json_encode([]));$this->SetBuffer('CurrentAreaID','0');}
    public function ApplyChanges(){parent::ApplyChanges();$this->RefreshAreas();}
    public function GetConfigurationForm(){return file_get_contents(__DIR__.'/form.json');}
    public function RequestAction($Ident,$Value){if($Ident==='SequenceActive'){(bool)$Value?$this->StartSequence():$this->StopSequence();return;}throw new Exception('Unbekannte Aktion: '.$Ident);}    
    public function CreateArea():void{$areas=$this->GetAreas();$n=1;$used=[];foreach($areas as $id){$used[]=@IRRA_GetAreaNumber($id);}while(in_array($n,$used,true))$n++;$id=IPS_CreateInstance(self::MODULE_ID_AREA);IPS_SetParent($id,$this->InstanceID);IPS_SetName($id,'Zone '.$n);IPS_SetPosition($id,1000+$n);IPS_SetProperty($id,'AreaNumber',$n);IPS_ApplyChanges($id);$this->RefreshAreas();$this->WriteLog('Zone '.$n.' angelegt');}
    public function RefreshAreas():void{$parts=[];foreach($this->GetAreas() as $id){$parts[]='Zone '.@IRRA_GetAreaNumber($id).' (#'.$id.')';} $this->SetValue('AreaOverview',implode('<br>',$parts));}
    public function StartSequence():void{$areas=[];foreach($this->GetAreas() as $id){if(@IRRA_IsEnabled($id))$areas[]=$id;}if(!$areas){$this->WriteLog('Keine aktiven Zonen');return;}$this->SetBuffer('AreaQueue',json_encode($areas));$this->SetValue('QueueCount',count($areas));$this->SetValue('SequenceActive',true);$this->SetPumpState(true);$this->WriteLog('Sequenz gestartet: '.count($areas).' Zone(n)');$lead=max(0,$this->ReadPropertyInteger('PumpLeadTimeSeconds'))*1000;$this->SetTimerInterval('StartNextAreaTimer',max(100,$lead));}
    public function StopSequence():void{$this->SetTimerInterval('StartNextAreaTimer',0);$id=(int)$this->GetBuffer('CurrentAreaID');if($id>0)@IRRA_StopArea($id,true);$this->SetBuffer('AreaQueue',json_encode([]));$this->SetBuffer('CurrentAreaID','0');$this->SetPumpState(false);$this->SetValue('SequenceActive',false);$this->SetValue('QueueCount',0);$this->SetValue('CurrentArea',0);$this->WriteLog('Sequenz gestoppt');}
    public function StartNextArea():void{$this->SetTimerInterval('StartNextAreaTimer',0);$q=json_decode($this->GetBuffer('AreaQueue'),true)?:[];if(!$q){$this->SetPumpState(false);$this->SetValue('SequenceActive',false);$this->SetValue('CurrentArea',0);$this->SetValue('QueueCount',0);$this->WriteLog('Sequenz abgeschlossen');return;}$id=array_shift($q);$this->SetBuffer('AreaQueue',json_encode($q));$this->SetBuffer('CurrentAreaID',(string)$id);$this->SetValue('CurrentArea',@IRRA_GetAreaNumber($id));$this->SetValue('QueueCount',count($q));$this->WriteLog('Starte Zone '.@IRRA_GetAreaNumber($id));@IRRA_StartArea($id,true);$this->FinishCurrentArea();}
    public function FinishCurrentArea():void{$q=json_decode($this->GetBuffer('AreaQueue'),true)?:[];if(!$q){$this->SetPumpState(false);$this->SetValue('SequenceActive',false);$this->WriteLog('Sequenz abgeschlossen');return;}$pause=max(0,$this->ReadPropertyInteger('PauseBetweenAreasSeconds'))*1000;$this->SetTimerInterval('StartNextAreaTimer',max(100,$pause));}
    private function GetAreas():array{$r=[];foreach(IPS_GetChildrenIDs($this->InstanceID) as $id){if(@IPS_InstanceExists($id)&&strtoupper(IPS_GetInstance($id)['ModuleInfo']['ModuleID']??'')===strtoupper(self::MODULE_ID_AREA))$r[]=$id;}usort($r,fn($a,$b)=>@IRRA_GetAreaNumber($a)<=>@IRRA_GetAreaNumber($b));return $r;}
    private function SetPumpState(bool $s):void{$id=$this->ReadPropertyInteger('PumpInstance')?:$this->ReadPropertyInteger('PumpVariable');if($id>0&&@IPS_ObjectExists($id)){try{RequestAction($id,$s);}catch(Throwable $e){}}$this->SetValue('PumpActive',$s);}    
    private function WriteLog(string $m):void{$a=[];$raw=strip_tags($this->GetValue('LastAction'));if($raw)$a=explode("\n",str_replace('<br>',"\n",$raw));$a[]='['.date('H:i:s').'] '.$m;$a=array_slice($a,-10);$this->SetValue('LastAction','<div style="font-family:Tahoma;font-size:12px;color:white;text-align:right;">'.implode('<br>',array_map('htmlspecialchars',$a)).'</div>');}
}
function IRR_CreateArea($id){IPS_GetInstance($id);return (new IrrigationController($id))->CreateArea();}
function IRR_RefreshAreas($id){return (new IrrigationController($id))->RefreshAreas();}
function IRR_StartSequence($id){return (new IrrigationController($id))->StartSequence();}
function IRR_StopSequence($id){return (new IrrigationController($id))->StopSequence();}
function IRR_StartNextArea($id){return (new IrrigationController($id))->StartNextArea();}
